// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto/brand.proto

package brandpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Brand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Country       string                 `protobuf:"bytes,4,opt,name=country,proto3" json:"country,omitempty"`
	Active        bool                   `protobuf:"varint,5,opt,name=active,proto3" json:"active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Brand) Reset() {
	*x = Brand{}
	mi := &file_proto_brand_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Brand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Brand) ProtoMessage() {}

func (x *Brand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_brand_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Brand.ProtoReflect.Descriptor instead.
func (*Brand) Descriptor() ([]byte, []int) {
	return file_proto_brand_proto_rawDescGZIP(), []int{0}
}

func (x *Brand) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Brand) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Brand) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Brand) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Brand) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

type BrandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BrandRequest) Reset() {
	*x = BrandRequest{}
	mi := &file_proto_brand_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrandRequest) ProtoMessage() {}

func (x *BrandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_brand_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrandRequest.ProtoReflect.Descriptor instead.
func (*BrandRequest) Descriptor() ([]byte, []int) {
	return file_proto_brand_proto_rawDescGZIP(), []int{1}
}

func (x *BrandRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_brand_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_brand_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_brand_proto_rawDescGZIP(), []int{2}
}

type BrandList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Brands        []*Brand               `protobuf:"bytes,1,rep,name=brands,proto3" json:"brands,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BrandList) Reset() {
	*x = BrandList{}
	mi := &file_proto_brand_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrandList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrandList) ProtoMessage() {}

func (x *BrandList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_brand_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrandList.ProtoReflect.Descriptor instead.
func (*BrandList) Descriptor() ([]byte, []int) {
	return file_proto_brand_proto_rawDescGZIP(), []int{3}
}

func (x *BrandList) GetBrands() []*Brand {
	if x != nil {
		return x.Brands
	}
	return nil
}

var File_proto_brand_proto protoreflect.FileDescriptor

const file_proto_brand_proto_rawDesc = "" +
	"\n" +
	"\x11proto/brand.proto\x12\x05proto\"\x7f\n" +
	"\x05Brand\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x18\n" +
	"\acountry\x18\x04 \x01(\tR\acountry\x12\x16\n" +
	"\x06active\x18\x05 \x01(\bR\x06active\"\x1e\n" +
	"\fBrandRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\a\n" +
	"\x05Empty\"1\n" +
	"\tBrandList\x12$\n" +
	"\x06brands\x18\x01 \x03(\v2\f.proto.BrandR\x06brands2q\n" +
	"\fBrandService\x12.\n" +
	"\fGetAllBrands\x12\f.proto.Empty\x1a\x10.proto.BrandList\x121\n" +
	"\fGetBrandByID\x12\x13.proto.BrandRequest\x1a\f.proto.BrandB\x11Z\x0f./proto;brandpbb\x06proto3"

var (
	file_proto_brand_proto_rawDescOnce sync.Once
	file_proto_brand_proto_rawDescData []byte
)

func file_proto_brand_proto_rawDescGZIP() []byte {
	file_proto_brand_proto_rawDescOnce.Do(func() {
		file_proto_brand_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_brand_proto_rawDesc), len(file_proto_brand_proto_rawDesc)))
	})
	return file_proto_brand_proto_rawDescData
}

var file_proto_brand_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_brand_proto_goTypes = []any{
	(*Brand)(nil),        // 0: proto.Brand
	(*BrandRequest)(nil), // 1: proto.BrandRequest
	(*Empty)(nil),        // 2: proto.Empty
	(*BrandList)(nil),    // 3: proto.BrandList
}
var file_proto_brand_proto_depIdxs = []int32{
	0, // 0: proto.BrandList.brands:type_name -> proto.Brand
	2, // 1: proto.BrandService.GetAllBrands:input_type -> proto.Empty
	1, // 2: proto.BrandService.GetBrandByID:input_type -> proto.BrandRequest
	3, // 3: proto.BrandService.GetAllBrands:output_type -> proto.BrandList
	0, // 4: proto.BrandService.GetBrandByID:output_type -> proto.Brand
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_brand_proto_init() }
func file_proto_brand_proto_init() {
	if File_proto_brand_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_brand_proto_rawDesc), len(file_proto_brand_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_brand_proto_goTypes,
		DependencyIndexes: file_proto_brand_proto_depIdxs,
		MessageInfos:      file_proto_brand_proto_msgTypes,
	}.Build()
	File_proto_brand_proto = out.File
	file_proto_brand_proto_goTypes = nil
	file_proto_brand_proto_depIdxs = nil
}
