// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: proto/seller.proto

package sellerpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SellerService_GetAllSellers_FullMethodName = "/proto.SellerService/GetAllSellers"
	SellerService_GetSellerByID_FullMethodName = "/proto.SellerService/GetSellerByID"
)

// SellerServiceClient is the client API for SellerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SellerServiceClient interface {
	GetAllSellers(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SellerList, error)
	GetSellerByID(ctx context.Context, in *SellerId, opts ...grpc.CallOption) (*Seller, error)
}

type sellerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSellerServiceClient(cc grpc.ClientConnInterface) SellerServiceClient {
	return &sellerServiceClient{cc}
}

func (c *sellerServiceClient) GetAllSellers(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SellerList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SellerList)
	err := c.cc.Invoke(ctx, SellerService_GetAllSellers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sellerServiceClient) GetSellerByID(ctx context.Context, in *SellerId, opts ...grpc.CallOption) (*Seller, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Seller)
	err := c.cc.Invoke(ctx, SellerService_GetSellerByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SellerServiceServer is the server API for SellerService service.
// All implementations must embed UnimplementedSellerServiceServer
// for forward compatibility.
type SellerServiceServer interface {
	GetAllSellers(context.Context, *Empty) (*SellerList, error)
	GetSellerByID(context.Context, *SellerId) (*Seller, error)
	mustEmbedUnimplementedSellerServiceServer()
}

// UnimplementedSellerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSellerServiceServer struct{}

func (UnimplementedSellerServiceServer) GetAllSellers(context.Context, *Empty) (*SellerList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllSellers not implemented")
}
func (UnimplementedSellerServiceServer) GetSellerByID(context.Context, *SellerId) (*Seller, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSellerByID not implemented")
}
func (UnimplementedSellerServiceServer) mustEmbedUnimplementedSellerServiceServer() {}
func (UnimplementedSellerServiceServer) testEmbeddedByValue()                       {}

// UnsafeSellerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SellerServiceServer will
// result in compilation errors.
type UnsafeSellerServiceServer interface {
	mustEmbedUnimplementedSellerServiceServer()
}

func RegisterSellerServiceServer(s grpc.ServiceRegistrar, srv SellerServiceServer) {
	// If the following call pancis, it indicates UnimplementedSellerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SellerService_ServiceDesc, srv)
}

func _SellerService_GetAllSellers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SellerServiceServer).GetAllSellers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SellerService_GetAllSellers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SellerServiceServer).GetAllSellers(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SellerService_GetSellerByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SellerId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SellerServiceServer).GetSellerByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SellerService_GetSellerByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SellerServiceServer).GetSellerByID(ctx, req.(*SellerId))
	}
	return interceptor(ctx, in, info, handler)
}

// SellerService_ServiceDesc is the grpc.ServiceDesc for SellerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SellerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.SellerService",
	HandlerType: (*SellerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAllSellers",
			Handler:    _SellerService_GetAllSellers_Handler,
		},
		{
			MethodName: "GetSellerByID",
			Handler:    _SellerService_GetSellerByID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/seller.proto",
}
